pool:
  name: 'Default'

steps:
- checkout: self

- script: cmd /c "python --version"
  displayName: "Verificar versão do Python"

- script: cmd /c "pip install -r requirements.txt && npm install -g snyk snyk-to-html && snyk test --file=requirements.txt --json > snyk-report.json || exit /b 0 && snyk-to-html -i snyk-report.json -o snyk-report.html"
  displayName: "Executar Snyk (relatório completo)"
  env:
    SNYK_TOKEN: $(SNYK_TOKEN)

# (Opcional) falhar se houver vulnerabilidades High/Critical
- script: cmd /c "snyk test --file=requirements.txt --severity-threshold=high"
  displayName: "Falhar se houver vulnerabilidades High/Critical"
  env:
    SNYK_TOKEN: $(SNYK_TOKEN)

- task: PublishBuildArtifacts@1
  displayName: "Guardar relatório HTML"
  inputs:
    pathToPublish: snyk-report.html
    artifactName: snyk-html-report


