trigger:
  - main  # corre automaticamente quando há push na main   

pool:
  name: 'Default'

variables:
  SNYK_TOKEN: $(SNYK_TOKEN)  # secret definido no portal do Azure DevOps

steps:
  - checkout: self

  - script: python --version
    displayName: "Verificar versão do Python"
    shell: cmd

  - script: |
      pip install -r requirements.txt
      npm install -g snyk snyk-to-html
      snyk test --file=requirements.txt --json > snyk-report.json || true
      snyk-to-html -i snyk-report.json -o snyk-report.html
    displayName: "Executar Snyk"
    shell: cmd
    env:
      SNYK_TOKEN: $(SNYK_TOKEN)
      
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'snyk-report.html'
      ArtifactName: 'snyk-html-report'
    displayName: "Guardar relatório HTML como artefacto"
