trigger:
  - main

pool:
  name: 'Default' 

steps:
  - checkout: self

  # Confirmar Python
  - script: python --version
    displayName: "Verificar versão do Python"

  - script: pip install -r requirements.txt
    displayName: "Instalar dependências"

  - script: npm install -g snyk snyk-to-html
    displayName: "Instalar Snyk e conversor HTML"

  - script: |
      echo A correr Snyk e a gerar relatório JSON...
      snyk test --file=requirements.txt --json > snyk-report.json || exit 0
    env:
      SNYK_TOKEN: $(SNYK_TOKEN)
    displayName: "Correr Snyk e gerar relatório completo"

  - script: |
      echo A verificar vulnerabilidades High/Critical...
      snyk test --file=requirements.txt --severity-threshold=high || exit 0
    env:
      SNYK_TOKEN: $(SNYK_TOKEN)
    displayName: "Verificar vulnerabilidades High/Critical"

  - script: snyk-to-html -i snyk-report.json -o snyk-report.html
    displayName: "Converter relatório em HTML"

  - task: SnykSecurityScan@1
    inputs:
      serviceConnectionEndpoint: 'Snyk Service Connection'
      testType: 'app'
      monitorWhen: 'always'
      failOnIssues: false
      projectName: 'MyApp'


  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: 'snyk-report.html'
      artifactName: 'snyk-html-report'
    displayName: "Guardar relatório HTML"

